/********************************************************************
* GuiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GuiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGuiDict();
extern void G__cpp_setup_inheritanceGuiDict();
extern void G__cpp_setup_typetableGuiDict();
extern void G__cpp_setup_memvarGuiDict();
extern void G__cpp_setup_globalGuiDict();
extern void G__cpp_setup_memfuncGuiDict();
extern void G__cpp_setup_funcGuiDict();
extern void G__set_cpp_environmentGuiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FitterGui.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GuiDictLN_TObject;
extern G__linked_taginfo G__GuiDictLN_string;
extern G__linked_taginfo G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiDictLN_TList;
extern G__linked_taginfo G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiDictLN_TQObjSender;
extern G__linked_taginfo G__GuiDictLN_TGWindow;
extern G__linked_taginfo G__GuiDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiDictLN_TGCompositeFrame;
extern G__linked_taginfo G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GuiDictLN_TGMainFrame;
extern G__linked_taginfo G__GuiDictLN_TGButtonGroup;
extern G__linked_taginfo G__GuiDictLN_TGRadioButton;
extern G__linked_taginfo G__GuiDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__GuiDictLN_TGNumberEntry;
extern G__linked_taginfo G__GuiDictLN_TGComboBox;
extern G__linked_taginfo G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiDictLN_TCanvas;
extern G__linked_taginfo G__GuiDictLN_TGHProgressBar;
extern G__linked_taginfo G__GuiDictLN_TGHSlider;
extern G__linked_taginfo G__GuiDictLN_FitterGui;

/* STUB derived class for protected member access */
