//
// File generated by rootcint at Thu Feb 12 08:08:51 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME GuiDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GuiDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void FitterGui_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void FitterGui_Dictionary();
   static void delete_FitterGui(void *p);
   static void deleteArray_FitterGui(void *p);
   static void destruct_FitterGui(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::FitterGui*)
   {
      ::FitterGui *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::FitterGui),0);
      static ::ROOT::TGenericClassInfo 
         instance("FitterGui", "./FitterGui.h", 134,
                  typeid(::FitterGui), DefineBehavior(ptr, ptr),
                  0, &FitterGui_Dictionary, isa_proxy, 0,
                  sizeof(::FitterGui) );
      instance.SetDelete(&delete_FitterGui);
      instance.SetDeleteArray(&deleteArray_FitterGui);
      instance.SetDestructor(&destruct_FitterGui);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::FitterGui*)
   {
      return GenerateInitInstanceLocal((::FitterGui*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FitterGui*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void FitterGui_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::FitterGui*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrapper around operator delete
   static void delete_FitterGui(void *p) {
      delete ((::FitterGui*)p);
   }
   static void deleteArray_FitterGui(void *p) {
      delete [] ((::FitterGui*)p);
   }
   static void destruct_FitterGui(void *p) {
      typedef ::FitterGui current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::FitterGui

/********************************************************
* GuiDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGuiDict();

extern "C" void G__set_cpp_environmentGuiDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("FitterGui.h");
  G__cpp_reset_tagtableGuiDict();
}
#include <new>
extern "C" int G__cpp_dllrevGuiDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FitterGui */
static int G__GuiDict_509_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const FitterGui*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((FitterGui*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((FitterGui*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((FitterGui*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((FitterGui*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((FitterGui*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((FitterGui*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((FitterGui*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((FitterGui*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((FitterGui*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   lval[icnt] = G__getstructoffset(); icnt++; // this pointer
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("EmitVA: more than 56 var args\n");
   }
      ((FitterGui*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FitterGui* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new FitterGui(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) FitterGui(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GuiDictLN_FitterGui));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoToyMC();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChooseToyMC();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChooseMinuit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoReadInputs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoFitter();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunFitter();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunToyMC();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunFlux();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunFitterTests();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->LoadResponseMatrix();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->LoadNominalPredictions();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->LoadToyMCSamples();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Update((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->UpdateFitter((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoSamples();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoCombine();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoBinning();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->CalculateBinning();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoNLModel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoFitterMode();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->Do1DFitterMode();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoAnalysis();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoNADs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoPeriod();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoNReactorPeriods();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotBkgd();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotADVis();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotADTrue();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotSpectrumFraction();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotFar();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotNear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotFarADTrue();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotNearADTrue();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotVariations();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotCov();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChooseCovarianceMatrix();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChoosePlotCov();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChoosePlotCovariance();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChoosePlotVariations();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChoosePlotRatioVariations();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChoosePlotSpectrumVariations();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotResponseMatrix();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChooseResponseMatrix();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->ChooseVariations();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotAccidental();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotLiHe();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotFN();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotAmC();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoNear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotCombine();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotAllADVis();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoNominal();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_80(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoChangeBin();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_81(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotErrorBudget();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_82(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotTurnOnBudget();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_83(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotTurnOffBudget();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_84(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunTurnOnBudget();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_85(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunTurnOffBudget();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_86(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->RunResponseMatrix();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_87(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoFits();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_88(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->PlotChi();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_89(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->GenerateToyMC();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_90(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoChangeSinSquareOscillationParameter();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_91(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoChangeDeltaSquareOscillationParameter();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_92(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoStatisticalFluctuation();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GuiDict_509_0_93(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitterGui*) G__getstructoffset())->DoUseToyMCSamples();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FitterGui G__TFitterGui;
static int G__GuiDict_509_0_94(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FitterGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FitterGui*) (soff+(sizeof(FitterGui)*i)))->~G__TFitterGui();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FitterGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FitterGui*) (soff))->~G__TFitterGui();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FitterGui */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGuiDict {
 public:
  G__Sizep2memfuncGuiDict(): p(&G__Sizep2memfuncGuiDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGuiDict::*p)();
};

size_t G__get_sizep2memfuncGuiDict()
{
  G__Sizep2memfuncGuiDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGuiDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGuiDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__GuiDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GuiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FitterGui */
static void G__setup_memvarFitterGui(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GuiDictLN_FitterGui));
   { FitterGui *p; p=(FitterGui*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TObject),-1,-1,4,"ChiH=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"AnalysisString=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"NominalString=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"CorrelationString=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"CovString=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"VarString=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGMainFrame),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fMaincanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fBackgroundcanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fADVisCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fADTrueCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fFractionCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fResponseCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fCovCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fChiCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fVariationsCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TRootEmbeddedCanvas),-1,-1,4,"fBudgetCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGHSlider),-1,-1,4,"hslider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGHSlider),-1,-1,4,"Sslider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGHSlider),-1,-1,4,"Dslider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"fCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"VCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"ADVisCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"ADTrueCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"ChiCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"FractionCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"ResponseCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"CovCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TCanvas),-1,-1,4,"BudgetCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGHProgressBar),-1,-1,4,"ToyMCProgressBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGHProgressBar),-1,-1,4,"FitterProgressBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGCompositeFrame),-1,-1,4,"fToyMCFrame2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGCompositeFrame),-1,-1,4,"fLoadInputs2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGCompositeFrame),-1,-1,4,"fFitterFrame2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"visible_bins=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"Period=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"NReactorPeriods=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"NADs=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"NSamples=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"CombineMode=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"NFits=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Analysis=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"flagCombine=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"flagNear=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"flagFar=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Binning=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"PlotBin=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Automatic=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"ToyMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Minuit=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"deleteFlag=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"deleteFlagSpec=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"MaxFar=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"MaxNear=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"NearTrueIndex=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"Sin22t13SliderValue=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"DeltaMSilderValue=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"UseToyMCTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Fit2D=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"FitSin22t13=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"VaryAccidentalMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"VaryLiHeMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"VaryFastNeutronsMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"VaryAmCMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"DistortLiHeMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"DistortFastNeutronsMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"DistortAmCMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"IsotopeMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"ReactorPowerMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"EnergyScaleMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"IAVMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"NLMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"ResolutionMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Sin22t12Matrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"EfficiencyMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"PlotCovariance=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGNumberEntry),-1,-1,4,"NSamplesBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGNumberEntry),-1,-1,4,"PeriodBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGNumberEntry),-1,-1,4,"NReactorPeriodBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGNumberEntry),-1,-1,4,"CombineBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGNumberEntry),-1,-1,4,"NFitsBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"VariationsBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"CorrelationBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"NLBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"NominalBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"IndexBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"FitterBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGButtonGroup),-1,-1,4,"Fitter1DBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"fR[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"fN[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"fI[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"fF[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"fV[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"fC[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGRadioButton),-1,-1,4,"f1DF[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"HGdBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"BinningBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"FluctuationBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"ToyMCTreeBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"NADsBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"ToyMCBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"MinuitBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"ResponseBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"CovarianceMatrixBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"CovariancePlotBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GuiDictLN_TGComboBox),-1,-1,4,"VariationsPlotBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"NL[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"FitterMode[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"Fitter1DMode[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"AutomaticBudget=",0,"To loop the fitter over all possible systematics");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"TurnOnBudget=",0,"Generates Turn On Error Budget");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"TurnOffBudget=",0,"Generates Turn Off Error Budget");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"StatisticalFluctuation=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"ResponseMatrixDirectory=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"ToyMCSampleDirectory=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"NominalPredictionsDirectory=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"SysCovarianceMatrixDirectory=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GuiDictLN_string),-1,-1,4,"BkgCovarianceMatrixDirectory=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGuiDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFitterGui(void) {
   /* FitterGui */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GuiDictLN_FitterGui));
   G__memfunc_setup("GetListOfSignals",1602,G__GuiDict_509_0_1, 85, G__get_linked_tagnum(&G__GuiDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__GuiDict_509_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__GuiDict_509_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__GuiDict_509_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__GuiDict_509_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__GuiDict_509_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GuiDict_509_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__GuiDict_509_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__GuiDict_509_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__GuiDict_509_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("delSpaces",916,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__GuiDictLN_string), -1, 0, 1, 1, 4, 0, "u 'string' - 1 - str", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FitterGui",915,G__GuiDict_509_0_27, 105, G__get_linked_tagnum(&G__GuiDictLN_FitterGui), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoToyMC",639,G__GuiDict_509_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChooseToyMC",1069,G__GuiDict_509_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChooseMinuit",1239,G__GuiDict_509_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoReadInputs",1202,G__GuiDict_509_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoFitter",801,G__GuiDict_509_0_32, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunFitter",931,G__GuiDict_509_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunToyMC",769,G__GuiDict_509_0_34, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunFlux",724,G__GuiDict_509_0_35, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunFitterTests",1462,G__GuiDict_509_0_36, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadResponseMatrix",1860,G__GuiDict_509_0_37, 121, -1, -1, 0, 0, 1, 1, 0, "", "To convert data to true energy", (void*) NULL, 0);
   G__memfunc_setup("LoadNominalPredictions",2258,G__GuiDict_509_0_38, 121, -1, -1, 0, 0, 1, 1, 0, "", "To fit and to create covariance matrices", (void*) NULL, 0);
   G__memfunc_setup("LoadToyMCSamples",1569,G__GuiDict_509_0_39, 121, -1, -1, 0, 0, 1, 1, 0, "", "To produce covariance matrices", (void*) NULL, 0);
   G__memfunc_setup("Update",611,G__GuiDict_509_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateFitter",1233,G__GuiDict_509_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSamples",904,G__GuiDict_509_0_42, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoCombine",880,G__GuiDict_509_0_43, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoBinning",888,G__GuiDict_509_0_44, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateBinning",1619,G__GuiDict_509_0_45, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNLModel",830,G__GuiDict_509_0_46, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoFitterMode",1190,G__GuiDict_509_0_47, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Do1DFitterMode",1307,G__GuiDict_509_0_48, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoAnalysis",1015,G__GuiDict_509_0_49, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNADs",505,G__GuiDict_509_0_50, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoPeriod",790,G__GuiDict_509_0_51, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNReactorPeriods",1703,G__GuiDict_509_0_52, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotBkgd",791,G__GuiDict_509_0_53, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotADVis",854,G__GuiDict_509_0_54, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotADTrue",964,G__GuiDict_509_0_55, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotSpectrumFraction",2088,G__GuiDict_509_0_56, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotFar",696,G__GuiDict_509_0_57, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotNear",805,G__GuiDict_509_0_58, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotFarADTrue",1245,G__GuiDict_509_0_59, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotNearADTrue",1354,G__GuiDict_509_0_60, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotVariations",1471,G__GuiDict_509_0_61, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotCov",711,G__GuiDict_509_0_62, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChooseCovarianceMatrix",2257,G__GuiDict_509_0_63, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChoosePlotCov",1320,G__GuiDict_509_0_64, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChoosePlotCovariance",2043,G__GuiDict_509_0_65, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChoosePlotVariations",2080,G__GuiDict_509_0_66, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChoosePlotRatioVariations",2591,G__GuiDict_509_0_67, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChoosePlotSpectrumVariations",2931,G__GuiDict_509_0_68, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotResponseMatrix",1891,G__GuiDict_509_0_69, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChooseResponseMatrix",2085,G__GuiDict_509_0_70, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChooseVariations",1665,G__GuiDict_509_0_71, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotAccidental",1415,G__GuiDict_509_0_72, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotLiHe",769,G__GuiDict_509_0_73, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotFN",563,G__GuiDict_509_0_74, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotAmC",656,G__GuiDict_509_0_75, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNear",569,G__GuiDict_509_0_76, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotCombine",1116,G__GuiDict_509_0_77, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotAllADVis",1135,G__GuiDict_509_0_78, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNominal",897,G__GuiDict_509_0_79, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoChangeBin",1042,G__GuiDict_509_0_80, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotErrorBudget",1540,G__GuiDict_509_0_81, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotTurnOnBudget",1632,G__GuiDict_509_0_82, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotTurnOffBudget",1726,G__GuiDict_509_0_83, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunTurnOnBudget",1526,G__GuiDict_509_0_84, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunTurnOffBudget",1620,G__GuiDict_509_0_85, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunResponseMatrix",1785,G__GuiDict_509_0_86, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoFits",585,G__GuiDict_509_0_87, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotChi",691,G__GuiDict_509_0_88, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateToyMC",1271,G__GuiDict_509_0_89, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoChangeSinSquareOscillationParameter",3766,G__GuiDict_509_0_90, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoChangeDeltaSquareOscillationParameter",3958,G__GuiDict_509_0_91, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoStatisticalFluctuation",2502,G__GuiDict_509_0_92, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoUseToyMCSamples",1665,G__GuiDict_509_0_93, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~FitterGui", 1041, G__GuiDict_509_0_94, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGuiDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGuiDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGuiDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GuiDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GuiDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGButtonGroup = { "TGButtonGroup" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGHProgressBar = { "TGHProgressBar" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_TGHSlider = { "TGHSlider" , 99 , -1 };
G__linked_taginfo G__GuiDictLN_FitterGui = { "FitterGui" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGuiDict() {
  G__GuiDictLN_TObject.tagnum = -1 ;
  G__GuiDictLN_string.tagnum = -1 ;
  G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GuiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GuiDictLN_TList.tagnum = -1 ;
  G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GuiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GuiDictLN_TQObjSender.tagnum = -1 ;
  G__GuiDictLN_TGWindow.tagnum = -1 ;
  G__GuiDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__GuiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GuiDictLN_TGCompositeFrame.tagnum = -1 ;
  G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GuiDictLN_TGMainFrame.tagnum = -1 ;
  G__GuiDictLN_TGButtonGroup.tagnum = -1 ;
  G__GuiDictLN_TGRadioButton.tagnum = -1 ;
  G__GuiDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__GuiDictLN_TGNumberEntry.tagnum = -1 ;
  G__GuiDictLN_TGComboBox.tagnum = -1 ;
  G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__GuiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GuiDictLN_TCanvas.tagnum = -1 ;
  G__GuiDictLN_TGHProgressBar.tagnum = -1 ;
  G__GuiDictLN_TGHSlider.tagnum = -1 ;
  G__GuiDictLN_FitterGui.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGuiDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_string);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TList);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGButtonGroup);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGHProgressBar);
   G__get_linked_tagnum_fwd(&G__GuiDictLN_TGHSlider);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GuiDictLN_FitterGui),sizeof(FitterGui),-1,33792,(char*)NULL,G__setup_memvarFitterGui,G__setup_memfuncFitterGui);
}
extern "C" void G__cpp_setupGuiDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGuiDict()");
  G__set_cpp_environmentGuiDict();
  G__cpp_setup_tagtableGuiDict();

  G__cpp_setup_inheritanceGuiDict();

  G__cpp_setup_typetableGuiDict();

  G__cpp_setup_memvarGuiDict();

  G__cpp_setup_memfuncGuiDict();
  G__cpp_setup_globalGuiDict();
  G__cpp_setup_funcGuiDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGuiDict();
  return;
}
class G__cpp_setup_initGuiDict {
  public:
    G__cpp_setup_initGuiDict() { G__add_setup_func("GuiDict",(G__incsetup)(&G__cpp_setupGuiDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGuiDict() { G__remove_setup_func("GuiDict"); }
};
G__cpp_setup_initGuiDict G__cpp_setup_initializerGuiDict;

